### ISSUE TITLE
Last 90 Days: no result - Uncaught (in promise) 

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi.ai#2886] opened 2019-08-27 15:04 UTC
- open susi.ai
- log in
- click on "Last 90 Days"

https://susi.ai/?creation_date&duration=90

-> no results a re shown. The following error appears in debugger:

![bug1](https://user-images.githubusercontent.com/238730/63783070-a7872600-c8ec-11e9-957d-e7957d3227cc.png)

**Comment by fragm3** [comment] 2019-08-28 04:43
@Orbiter unable to reproduce the bug.

**Comment by harsh-jindal** [comment] 2019-08-28 11:49
@Orbiter Unable to reproduce bug. Can be fixed if reproduced by someone later.

**Comment by akshatnitd** [comment] 2020-01-15 17:07
Can't reproduce this issue. Closing it.

**Closed by akshatnitd** 2020-01-15 17:07 UTC
Labels: bug
