### ISSUE TITLE
Fallback message on not finding a skill has unordered list not aligned.

### ISSUE THREAD

**Issue by arteevraina** [fossasia/susi.ai#3528] opened 2020-05-09 20:02 UTC
**Actual Behaviour**

When you search skills in `search bar`. It renders unordered list with list items not in proper alignment.

**Expected Behaviour**

Unordered List items should be properly aligned.

**Steps to reproduce it**

 - Go to the [demo](https://susi.ai/).
 - Search anything in `searchbar`.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/43968121/81483693-b127a280-925d-11ea-98f2-f1836d296689.png)

**Would you like to work on the issue?**

Yes I would like to work on this issue.

**Comment by anandgupta887** [comment] 2020-05-10 17:55
Yes I would like to work on this issue

**Comment by arteevraina** [comment] 2020-05-10 17:58
@anandgupta887 Sure! Work on this.

**Comment by anandgupta887** [comment] 2020-05-11 02:27
Is it the expected result or you need the list to indented?

![Screenshot_3](https://user-images.githubusercontent.com/58431092/81518835-f383d900-935c-11ea-8576-f2c79bceac48.png)

**Comment by snitin315** [comment] 2020-05-11 02:29
Yep, you can send PR.

**Comment by anandgupta887** [comment] 2020-05-11 06:47
I have posted PR. Please have a check.
Pull Request -- #3535

**Comment by anishagg17** [comment] 2020-05-14 08:32
Duplicate of #3093

**Closed** 2020-05-21 17:39 UTC
