### ISSUE TITLE
Sorting skill by Name(A-Z) is sorting in (Z-A) 

### ISSUE THREAD

**Issue by aman29271** [fossasia/susi.ai#3008] opened 2019-10-30 10:40 UTC
**Actual Behaviour**

Sorting Susi skill by Name(A-Z) is instead sorting in (Z-A)

**Expected Behaviour**

It should sort in Name(A-Z) order.

**Steps to reproduce it**

Go to https://susi.ai/category/All 
And Select sort by to Name(A-Z).

**Screenshots of the issue**

![Screenshot from 2019-10-30 16-05-47](https://user-images.githubusercontent.com/30979779/67850981-7bc42e80-fb2f-11e9-9ff9-5ab9183f68eb.png)

**Would you like to work on the issue?**

Yes

**Comment by plxity** [comment] 2019-11-03 16:48
@aman29271 are you working on this? or can I take this up?

**Comment by plxity** [comment] 2019-11-05 17:43
@aman29271 I am taking this up.

**Comment by plxity** [comment] 2019-11-05 17:57
@aman29271 That is not an issue. The arrow adjacent to dropdown shows whether it's descending or
ascending.
@akshatnitd We shall close this up.

**Comment by akshatnitd** [comment] 2019-11-06 05:36
@pipix51 The issue is valid. The default behaviour when we select `Name(A-Z)` should be ascending.

**Comment by kpulkit29** [comment] 2019-11-09 13:30
@aman29271  are you still working on it?

**Comment by aman29271** [comment] 2019-11-09 17:17
@kpulkit29 yes

**Comment by Dishebh** [comment] 2020-01-03 15:36
@aman29271 can I take the issue pls?

**Comment by aman29271** [comment] 2020-01-05 09:37
@Dishebh go ahead

**Comment by NitinBhasneria** [comment] 2020-01-07 11:27
@aman29271 Looks like @Dishebh has taken many issues and not working so can I take this issue?
@Dishebh If you are working then please respond...

**Comment by Dishebh** [comment] 2020-01-07 11:39
@NitinBhasneria working on it.

**Comment by anishagg17** [comment] 2020-01-11 12:24
@aman29271 can I take the issue pls?
@Dishebh It's more than 4 days no effort has been shown by you

**Comment by Dishebh** [comment] 2020-01-11 12:36
Sure, go ahead.

**Comment by ShubhamChaudharyy** [comment] 2020-01-14 15:47
@aman29271 if u aren't working on this issue can i take up?

**Comment by anishagg17** [comment] 2020-01-15 18:51
@ShubhamChaudharyy i am working on it

**Comment by NimishGopal** [comment] 2020-01-17 13:22
@anishagg17 Are you working on it? If not, please give me a go-ahead.

**Closed** 2020-01-17 20:35 UTC
