### ISSUE TITLE
Compilation error upon npm run while local hosting the server

### ISSUE THREAD

**Issue by guptarohan811** [fossasia/susi.ai#3069] opened 2019-11-17 03:52 UTC
**Actual Behaviour**

The page shows compilation error upon running the susi ai on local host using "npm run start" due to files missing. Problem still persistent upon several re installations. Can anyone please help @akshatnitd 

**Expected Behaviour**

Should have run successfully on local host without error.

**Screenshots of the issue**

![Screenshot from 2019-11-17 09-19-45](https://user-images.githubusercontent.com/54477568/69002839-ad553c00-091c-11ea-9b30-bcfb8976a12d.png)

**Would you like to work on the issue?**

**Comment by AdityaSrivast** [comment] 2019-11-18 06:58
@guptarohan811 did you try running `npm install` before starting the server? It may be possible because of missing dependencies.

**Comment by guptarohan811** [comment] 2019-11-18 07:24
> @guptarohan811 did you try running `npm install` before starting the server? It may be possible because of missing dependencies.

Yeah i have followed all the steps given in the docs

**Comment by akshatnitd** [comment] 2020-01-15 17:02
Can't reproduce this issue. Closing it.

**Closed by akshatnitd** 2020-01-15 17:02 UTC
