### ISSUE TITLE
unable to create account on sus.ai

### ISSUE THREAD

**Issue by royan0007** [fossasia/susi.ai#3109] opened 2019-12-15 11:54 UTC
**Actual Behaviour**

**Expected Behaviour**

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

**Comment by royan0007** [comment] 2019-12-16 13:18
i am unable to login on sus.ai

**Comment by plxity** [comment] 2019-12-27 20:42
@royan0007 Signup functionality is working fine. Try signing up again.

**Comment by akshatnitd** [comment] 2020-01-15 17:00
Can't reproduce this issue. Closing it.

**Closed by akshatnitd** 2020-01-15 17:00 UTC
