### ISSUE TITLE
The sideBar disappears at width less than 770px. I think It would be better to have a burger menu to open the sidebar on smaller screens.

### ISSUE THREAD

**Issue by lopeselio** [fossasia/susi.ai#3590] opened 2020-07-25 17:06 UTC
**Actual Behaviour**
**The sideBar disappears at width less than 770px. I think It would be better to have a burger menu to open the sidebar on smaller screens.**

**Expected Behaviour**
_**I think It would be better to have a burger menu to open the sidebar on smaller screens.**_

**Steps to reproduce it**
1. Head over to https://susi.ai/
2. Inspect the screen for smaller screen width. Note that the side Navigation containing create and new arrivals disappears, but should be visible on the click of a burger menu button which may be installed on the main navbar.

**LogCat for the issue**

**Screenshots of the issue**
screen width greater than 770px
![susi1](https://user-images.githubusercontent.com/43913734/88462188-16874900-cec7-11ea-9a36-f0c40a96c51f.png)

screen width less than 770px
![susi2](https://user-images.githubusercontent.com/43913734/88462197-2ef76380-cec7-11ea-8d93-16e445cd4932.png)

**Would you like to work on the issue?**
Yes, but not currently.

**Comment by Swayamsvk** [comment] 2020-07-29 20:31
Can I work on this issue?

**Comment by lopeselio** [comment] 2020-07-30 06:41
Can I work on this issue >?

**Comment by Swayamsvk** [comment] 2020-07-30 11:44
> Can I work on this issue >?

It's ok if you are working on it I will try something else.

**Comment by snitin315** [comment] 2020-07-30 11:51
No need to ask, just send PR if no one else is working.

**Comment by Sayan-dev** [comment] 2020-08-15 07:10
Let me work on it

**Comment by snitin315** [comment] 2020-08-15 07:27
Go ahead

**Comment by padmaja-12** [comment] 2020-08-29 07:38
can i work on this issue?

**Comment by ksraj123** [comment] 2020-09-29 11:00
I think the Hamburger icon and sidebar is implemented for screen width below 520 px but width between 520px to 768px the sidebar disappears and we don't have a hamburger icon as mentioned in issue #3594 
This is being fixed in #3600

**Comment by akshatnitd** [comment] 2020-10-27 11:55
Duplicate of #3594 .

**Closed by akshatnitd** 2020-10-27 11:55 UTC
