### ISSUE TITLE
Reviewed skills need to include a picture

### ISSUE THREAD

**Issue by tabesin** [fossasia/susi.ai#2571] opened 2019-07-15 16:58 UTC
**Actual Behaviour**

Lots of skills are reviewed but do not even include a picture. that looks bad.

**Expected Behaviour**

Reviewed skills need to have a picture.

**Steps to reproduce it**

https://susi.ai/category/All

**Screenshots of the issue**
![reviewed](https://user-images.githubusercontent.com/10114907/61234104-8ac6d280-a732-11e9-9ab4-0ce28b40313a.png)

**Would you like to work on the issue?**

**Comment by mariobehling** [comment] 2019-07-15 20:57
These reviews are done according to functionality. This is easy to solve by logged in users. It is an opinion, not a bug. Therefore closing it.

**Closed by mariobehling** 2019-07-15 20:57 UTC
