### ISSUE TITLE
Alignment of sidemenu is not remaining same 

### ISSUE THREAD

**Issue by chauhanparth210** [fossasia/susi.ai#2904] opened 2019-09-09 08:13 UTC
**Actual Behaviour**
While clicking on Settings->User API Keys the alignment of the sidemenu will change.

**Expected Behaviour**
It Should remain same as before

**Screenshots of the issue**
![Screenshot (38)](https://user-images.githubusercontent.com/35137224/64514005-6a1c9280-d307-11e9-938a-c708e954fa91.png)

**Alignment of the sidemenu not remaining same**

![Screenshot (39)](https://user-images.githubusercontent.com/35137224/64514009-6ee14680-d307-11e9-9b08-a865a596710b.png)

**Would you like to work on the issue?**
Yes

**Comment by Dilshaad21** [comment] 2019-09-23 12:41
@chauhanparth210 can I take this issue?

**Comment by chauhanparth210** [comment] 2019-09-23 14:13
@Dilshaad21  no I am  working on it....

**Comment by akshat0047** [comment] 2019-10-30 21:01
I would like to work on it @mariobehling

**Comment by akshat0047** [comment] 2019-10-30 21:18
I would like to take this

**Comment by akshat0047** [comment] 2019-11-03 15:57
![already-fixed](https://user-images.githubusercontent.com/32462195/68087945-83157000-fe80-11e9-950a-f366c2853edd.gif)

I think this is already fixed, unable to reproduce it. We shall close this.
@iamareebjamal @akshatnitd

**Comment by akshat0047** [comment] 2019-11-08 15:37
Its been reproduced now, don't  know how, on it

**Comment by akshatnitd** [comment] 2020-01-15 17:07
Can't reproduce this issue. Closing it.

**Closed by akshatnitd** 2020-01-15 17:07 UTC
Labels: bug
